# Generated by Django 5.2.1 on 2025-05-29 20:32

import lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=64, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[lib.validators.RussianPhoneNumberValidator], verbose_name='Номер телефона'),
        ),
    ]
