# Generated by Django 5.2.1 on 2025-05-30 14:11

import django.db.models.deletion
from lib.validators import RussianPhoneNumberValidator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_patronymic_user_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[RussianPhoneNumberValidator()], verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.TextField(verbose_name='Адрес')),
                ('phonenumber', models.CharField(validators=[RussianPhoneNumberValidator()], verbose_name='Номер телефона')),
                ('service', models.CharField(max_length=32, verbose_name='Тип услуг')),
                ('date', models.DateTimeField(verbose_name='Дата получения услуги')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('isCustom', models.BooleanField(default=False, verbose_name='Своя услуга?')),
                ('customService', models.CharField(blank=True, max_length=64, verbose_name='Своя услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'request',
            },
        ),
    ]
