# Generated by Django 5.2.1 on 2025-05-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phonenumber_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='addres',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='request',
            name='customService',
        ),
    ]
