# Generated by Django 5.2.1 on 2025-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_addres_request_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payType',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта')], default='cash', verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('done', 'Услуга оказана'), ('cancelled', 'Услуга отменена')], default='new', verbose_name='Статус заявки'),
        ),
    ]
