# Generated by Django 5.2.1 on 2025-05-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_request_paytype_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
